---
name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.3
        with:
          tools-deps: "latest"

      - name: Show Clojure env details
        run: clojure -Sdescribe

      - name: Run tests
        run: lein test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.3
        with:
          tools-deps: "latest"

      - name: Show Clojure env details
        run: clojure -Sdescribe

      - name: Lint with clj-kondo
        run: lein clj-kondo --lint src/ test/

